In [1]:
import os
import numpy as np
import pandas as pd
from scipy.stats import weibull_min
from OpenFAST_IO import OpenFASTOutput, OpenFASTBinary, OpenFASTAscii
from OpenFAST_Processors import pyLife

In [2]:
filepath = os.path.join("/Users/jnunemak/Desktop/repos/openfast-post-processors-dev/orig/mlife/CertTest/Data/DLC1.1_01_small.out")
output = OpenFASTAscii(filepath)
output.read()

In [3]:
output.channels

array(['Time', 'WindVxi', 'GenPwr', 'RotSpeed', 'OoPDefl1', 'IPDefl1',
       'OoPDefl2', 'IPDefl2', 'OoPDefl3', 'IPDefl3', 'RootFxc1',
       'RootFyc1', 'RootFzc1', 'RotTorq'], dtype='<U8')

In [11]:
filepath = os.path.join("/Users/jnunemak/Desktop/repos/openfast-post-processors-dev/orig/mlife/CertTest/Data/")

life = pyLife(filepath, files=["DLC2.3_1.out"], max_bin_size=2, ws_max=31)
life.read_files()

In [13]:
bounds, prob = life.compute_windspeed_bins()
prob

array([2.22487628e-02, 6.38200519e-02, 1.35130402e-01, 1.66174389e-01,
       1.67768328e-01, 1.46660787e-01, 1.13677755e-01, 7.91202994e-02,
       4.98230120e-02, 2.85243657e-02, 1.48966685e-02, 7.11341807e-03,
       3.11130612e-03, 1.24812608e-03, 4.59698196e-04, 1.55575033e-04])

In [14]:
bounds

array([ 1.5,  3. ,  5. ,  7. ,  9. , 11. , 13. , 15. , 17. , 19. , 21. ,
       23. , 25. , 27. , 29. , 31. ])

In [15]:
mean = 5.1
np.where(bounds < mean)

(array([0, 1, 2]),)

In [17]:
len(bounds)

23

In [5]:
filepath = os.path.join("/Users/jnunemak/Desktop/repos/openfast-post-processors-dev/orig/mlife/CertTest/NREL_Results/Test02/DLC2.3_1_Statistics.txt")

data = []
keep = False
with open(filepath, "rb") as f:
    
    for i, _line in enumerate(f):
        line = _line.replace(b"\xb7", b"-").decode().strip()
        
        if line.startswith("Channel"):
            break
            
            
data = pd.read_csv(filepath, skiprows=i, delim_whitespace=True)
data.tail(10)
        

Channel   Minimum         Mean    Maximum       StdDev  Skewness  \
125   Fair8Ten  200.0000   214.640000   263.0000    15.138000  1.306200   
126   Fair8Ang   71.8000    80.572000    83.8000     3.174400 -1.104300   
127   Anch8Ten    0.0000     0.000000     0.0000     0.000000  0.000000   
128   Anch8Ang    0.0000     0.000000     0.0000     0.000000  0.000000   
129  TipSpdRat   -0.0346     4.509100     8.8300     3.237600 -0.434680   
130      RotCp   -0.2150     0.196910     0.4660     0.212810 -0.071073   
131      RotCt   -0.6150     0.516610     1.1300     0.476320 -0.757930   
132      RotCq   -0.0274     0.026532     0.0624     0.030894 -0.087672   
133  RootFMxy1   29.0660   174.530000   300.3700    69.021000 -0.070736   
134  RootMMxy1  459.7800  5018.900000  9134.1000  2673.200000 -0.093513   

     Kurtosis      Range  
125    3.9955    63.0000  
126    3.3336    12.0000  
127    0.0000     0.0000  
128    0.0000     0.0000  
129    1.3610     8.8646  
130    1.1464     0.6810  
131    2.2171     1.7450  
132    1.1274     0.0898  
133    1.8309   271.3100  
134    1.3498  8674.3000

In [6]:
np.allclose(life.minima, data["Minimum"], rtol=1)

False

In [7]:
life.minima

array([ 3.00000000e+01,  8.20000000e+00,  0.00000000e+00,  0.00000000e+00,
       -8.12000000e-01, -5.42000000e-01,  0.00000000e+00, -7.48000000e-01,
       -7.23000000e-01,  0.00000000e+00, -8.32000000e-01,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  7.56000000e-02, -4.93000000e-02, -4.82000000e+00,
       -2.13000000e-02, -5.07000000e-01, -2.09000000e+00, -9.38000000e-01,
        0.00000000e+00, -3.08000000e+00, -8.94000000e-01,  0.00000000e+00,
       -3.44000000e+00, -1.23000000e+00,  0.00000000e+00,  9.61000000e+00,
        9.39000000e+00,  9.52000000e+00, -2.25000000e+00, -1.32000000e-01,
       -4.79000000e-01, -8.20000000e-01, -5.22000000e-02,  0.00000000e+00,
        4.77000000e+00, -1.30000000e-01, -1.01000000e+00, -1.14000000e-01,
       -5.44000000e+00, -1.29000000e+00, -3.51000000e-01, -1.92000000e-02,
       -3.52000000e-01, -1.27000000e+02, -2.12000000e+02,  1.13000000e+02,
       -3.77000000e+03, -

In [38]:
data["Minimum"]

0       30.0000
1        8.2000
2        0.0000
3        0.0000
4        0.1880
         ...   
130     -0.2150
131     -0.6150
132     -0.0274
133     29.0660
134    459.7800
Name: Minimum, Length: 135, dtype: float64

In [93]:
life.data

AttributeError: 'pyLife' object has no attribute 'data'

In [9]:
np.isclose(life.minima, data["Minimum"], rtol=0.01)

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [11]:
life.channels

array(['Time', 'WindVxi', 'WindVyi', 'WindVzi', 'WaveElev', 'Wave1Vxi',
       'Wave1Vyi', 'Wave1Vzi', 'Wave1Axi', 'Wave1Ayi', 'Wave1Azi',
       'GenPwr', 'GenTq', 'HSSBrTq', 'BldPitch1', 'BldPitch2',
       'BldPitch3', 'Azimuth', 'RotSpeed', 'GenSpeed', 'NacYaw',
       'NacYawErr', 'OoPDefl1', 'IPDefl1', 'TwstDefl1', 'OoPDefl2',
       'IPDefl2', 'TwstDefl2', 'OoPDefl3', 'IPDefl3', 'TwstDefl3',
       'TwrClrnc1', 'TwrClrnc2', 'TwrClrnc3', 'NcIMUTAxs', 'NcIMUTAys',
       'NcIMUTAzs', 'TTDspFA', 'TTDspSS', 'TTDspTwst', 'PtfmSurge',
       'PtfmSway', 'PtfmHeave', 'PtfmRoll', 'PtfmPitch', 'PtfmYaw',
       'PtfmTAxt', 'PtfmTAyt', 'PtfmTAzt', 'RootFxc1', 'RootFyc1',
       'RootFzc1', 'RootMxc1', 'RootMyc1', 'RootMzc1', 'RootFxc2',
       'RootFyc2', 'RootFzc2', 'RootMxc2', 'RootMyc2', 'RootMzc2',
       'RootFxc3', 'RootFyc3', 'RootFzc3', 'RootMxc3', 'RootMyc3',
       'RootMzc3', 'Spn1MLxb1', 'Spn1MLyb1', 'Spn1MLzb1', 'Spn1MLxb2',
       'Spn1MLyb2', 'Spn1MLzb2', 'Spn1MLxb3', 'Spn1

In [38]:
data

Channel    Minimum         Mean     Maximum       StdDev  Skewness  \
0         Time   30.00000    60.000000    90.00000    17.342000  0.000000   
1      WindVxi    8.19700     9.449400    12.72000     0.600070  3.359600   
2      WindVyi    0.00000     0.000000     0.00000     0.000000  0.000000   
3      WindVzi    0.00000     0.000000     0.00000     0.000000  0.000000   
4     WaveElev   -0.05500     1.004400     1.86330     0.545010 -0.203630   
..         ...        ...          ...         ...          ...       ...   
130      RotCp   -0.21930     0.200870     0.48010     0.217370 -0.063715   
131      RotCt   -0.68750     0.529240     1.17100     0.506780 -0.909380   
132      RotCq   -0.02778     0.026894     0.06365     0.031315 -0.085106   
133  RootFMxy1   18.63700   179.210000   303.90000    66.810000 -0.185490   
134  RootMMxy1  277.60000  5134.800000  9079.30000  2644.700000 -0.121500   

     Kurtosis       Range  
0      1.8000    60.00000  
1     18.3310     4.52300  
2      0.0000     0.00000  
3      0.0000     0.00000  
4      1.8456     1.91830  
..        ...         ...  
130    1.1569     0.69940  
131    2.3828     1.85850  
132    1.1317     0.09143  
133    2.1203   285.27000  
134    1.3650  8801.70000  

[135 rows x 8 columns]

In [40]:
np.sqrt(output.data[:, 50] ** 2 + output.data[:, 51] ** 2).mean()

334.7076569480211

In [23]:
data = pd.read_csv(filepath, skiprows=5, delim_whitespace=True)
data

Channel  Minimum  Mean  Maximum  StdDev  Skewness  Kurtosis  Range
0  DLC2.3_1     -127   108      250    98.2    -0.401      1.79    377

In [4]:
test.description

'These predictions were generated by FAST (v6.10a-jmj, 21-Feb-2007) on 01-Apr-2007 at 16:55:28. The aerodynamic calculations were made by AeroDyn (12.60i-pjm, 16-Nov-2006).  NREL 5.0 MW Baseline Wind Turbine for Use in Offshore Analysis.'

In [17]:
test.kurtosis

array([[1.79999998, 2.49719635, 2.55819379, 2.41119936, 3.10623597,
        1.56788597, 3.09467569, 1.5697641 , 3.07628282, 1.57114124,
        3.13778693, 1.50231245, 1.56663858, 2.43617668]])

In [4]:
a

2

In [129]:
_start = False
header = []
with open(filepath, "rb") as f:
    for _line in f:

        line = _line.replace(b'\xb7', b'-').decode().strip()
        header.append(line)
        
        if _start:
            break
        
        if line.startswith("Time"):
            _start = True

In [143]:
descr = " ".join([h.replace('"', '') for h in header[:-2]]).strip()
descr

'These predictions were generated by FAST (v6.10a-jmj, 21-Feb-2007) on 01-Apr-2007 at 20:37:44. The aerodynamic calculations were made by AeroDyn (12.60i-pjm, 16-Nov-2006).  NREL 5.0 MW Baseline Wind Turbine for Use in Offshore Analysis.'

In [145]:
header[-2:]

['Time\tWindVxi\tWindVyi\tWindVzi\tWaveElev\tWave1Vxi\tWave1Vyi\tWave1Vzi\tWave1Axi\tWave1Ayi\tWave1Azi\tGenPwr\tGenTq\tHSSBrTq\tBldPitch1\tBldPitch2\tBldPitch3\tAzimuth\tRotSpeed\tGenSpeed\tNacYaw\tNacYawErr\tOoPDefl1\tIPDefl1\tTwstDefl1\tOoPDefl2\tIPDefl2\tTwstDefl2\tOoPDefl3\tIPDefl3\tTwstDefl3\tTwrClrnc1\tTwrClrnc2\tTwrClrnc3\tNcIMUTAxs\tNcIMUTAys\tNcIMUTAzs\tTTDspFA\tTTDspSS\tTTDspTwst\tPtfmSurge\tPtfmSway\tPtfmHeave\tPtfmRoll\tPtfmPitch\tPtfmYaw\tPtfmTAxt\tPtfmTAyt\tPtfmTAzt\tRootFxc1\tRootFyc1\tRootFzc1\tRootMxc1\tRootMyc1\tRootMzc1\tRootFxc2\tRootFyc2\tRootFzc2\tRootMxc2\tRootMyc2\tRootMzc2\tRootFxc3\tRootFyc3\tRootFzc3\tRootMxc3\tRootMyc3\tRootMzc3\tSpn1MLxb1\tSpn1MLyb1\tSpn1MLzb1\tSpn1MLxb2\tSpn1MLyb2\tSpn1MLzb2\tSpn1MLxb3\tSpn1MLyb3\tSpn1MLzb3\tRotThrust\tLSSGagFya\tLSSGagFza\tRotTorq\tLSSGagMya\tLSSGagMza\tYawBrFxp\tYawBrFyp\tYawBrFzp\tYawBrMxp\tYawBrMyp\tYawBrMzp\tTwrBsFxt\tTwrBsFyt\tTwrBsFzt\tTwrBsMxt\tTwrBsMyt\tTwrBsMzt\tTwHt1MLxt\tTwHt1MLyt\tTwHt1MLzt\tFair1Ten\tFair1An

In [133]:
columns = [a for a in header[-2].split("\t")]
units = [b for b in header[-1].split("\t")]

headers = list(zip(columns, units))
headers

[('Time', '(sec)'),
 ('WindVxi', '(m/sec)'),
 ('WindVyi', '(m/sec)'),
 ('WindVzi', '(m/sec)'),
 ('WaveElev', '(m)'),
 ('Wave1Vxi', '(m/sec)'),
 ('Wave1Vyi', '(m/sec)'),
 ('Wave1Vzi', '(m/sec)'),
 ('Wave1Axi', '(m/sec^2)'),
 ('Wave1Ayi', '(m/sec^2)'),
 ('Wave1Azi', '(m/sec^2)'),
 ('GenPwr', '(kW)'),
 ('GenTq', '(kN-m)'),
 ('HSSBrTq', '(kN-m)'),
 ('BldPitch1', '(deg)'),
 ('BldPitch2', '(deg)'),
 ('BldPitch3', '(deg)'),
 ('Azimuth', '(deg)'),
 ('RotSpeed', '(rpm)'),
 ('GenSpeed', '(rpm)'),
 ('NacYaw', '(deg)'),
 ('NacYawErr', '(deg)'),
 ('OoPDefl1', '(m)'),
 ('IPDefl1', '(m)'),
 ('TwstDefl1', '(deg)'),
 ('OoPDefl2', '(m)'),
 ('IPDefl2', '(m)'),
 ('TwstDefl2', '(deg)'),
 ('OoPDefl3', '(m)'),
 ('IPDefl3', '(m)'),
 ('TwstDefl3', '(deg)'),
 ('TwrClrnc1', '(m)'),
 ('TwrClrnc2', '(m)'),
 ('TwrClrnc3', '(m)'),
 ('NcIMUTAxs', '(m/sec^2)'),
 ('NcIMUTAys', '(m/sec^2)'),
 ('NcIMUTAzs', '(m/sec^2)'),
 ('TTDspFA', '(m)'),
 ('TTDspSS', '(m)'),
 ('TTDspTwst', '(deg)'),
 ('PtfmSurge', '(m)'),
 ('PtfmSway

In [132]:
header[-2].split("\t")

['Time',
 'WindVxi',
 'WindVyi',
 'WindVzi',
 'WaveElev',
 'Wave1Vxi',
 'Wave1Vyi',
 'Wave1Vzi',
 'Wave1Axi',
 'Wave1Ayi',
 'Wave1Azi',
 'GenPwr',
 'GenTq',
 'HSSBrTq',
 'BldPitch1',
 'BldPitch2',
 'BldPitch3',
 'Azimuth',
 'RotSpeed',
 'GenSpeed',
 'NacYaw',
 'NacYawErr',
 'OoPDefl1',
 'IPDefl1',
 'TwstDefl1',
 'OoPDefl2',
 'IPDefl2',
 'TwstDefl2',
 'OoPDefl3',
 'IPDefl3',
 'TwstDefl3',
 'TwrClrnc1',
 'TwrClrnc2',
 'TwrClrnc3',
 'NcIMUTAxs',
 'NcIMUTAys',
 'NcIMUTAzs',
 'TTDspFA',
 'TTDspSS',
 'TTDspTwst',
 'PtfmSurge',
 'PtfmSway',
 'PtfmHeave',
 'PtfmRoll',
 'PtfmPitch',
 'PtfmYaw',
 'PtfmTAxt',
 'PtfmTAyt',
 'PtfmTAzt',
 'RootFxc1',
 'RootFyc1',
 'RootFzc1',
 'RootMxc1',
 'RootMyc1',
 'RootMzc1',
 'RootFxc2',
 'RootFyc2',
 'RootFzc2',
 'RootMxc2',
 'RootMyc2',
 'RootMzc2',
 'RootFxc3',
 'RootFyc3',
 'RootFzc3',
 'RootMxc3',
 'RootMyc3',
 'RootMzc3',
 'Spn1MLxb1',
 'Spn1MLyb1',
 'Spn1MLzb1',
 'Spn1MLxb2',
 'Spn1MLyb2',
 'Spn1MLzb2',
 'Spn1MLxb3',
 'Spn1MLyb3',
 'Spn1MLzb3',
 'RotThr

In [81]:
line.startswith("Time")

TypeError: startswith first arg must be bytes or a tuple of bytes, not str

In [61]:
f.readline()

ValueError: readline of closed file

In [ ]:
pd.read_csv(filepat)