### Classes for working with OpenFAST Outputs

Jake Nunemaker

National Renewable Energy Lab

In [1]:
import os
import pandas as pd

from OpenFAST_IO import OpenFASTOutput, OpenFASTBinary, OpenFASTAscii

ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
DATA = os.path.join(ROOT, "tests", "data")

#### Reading OpenFAST Binary and ASCII Outputs

In [2]:
# OpenFASTBinary and OpenFASTAscii are used to load file based OpenFASt outputs
filepath = os.path.join(DATA, "IEA15MW_DLC_ED_000.outb")
output = OpenFASTBinary(filepath)
output.read()
print(output)

Predictions were generated on 07-Jul-2020 at 21:55:36 using OpenFAST, compiled as a 64-bit application using single precision at commit v2.2.0-10-g6d9e2b9f linked with  NWTC Subroutine Library; ElastoDyn; InflowWind; AeroDyn; ServoDyn; HydroDyn; Description from the FAST input file: Generated with AeroElasticSE FAST driver


In [3]:
# Data can be output as a numpy array or a panda DataFrame:

output.data  # numpy array
# output.df    # pandas DataFrame

array([[ 1.00000000e+02,  2.50940251e+00, -5.76725006e-01, ...,
         0.00000000e+00,  0.00000000e+00, -1.51300535e-01],
       [ 1.00010000e+02,  2.50962973e+00, -6.03225768e-01, ...,
         0.00000000e+00,  0.00000000e+00, -1.53117880e-01],
       [ 1.00020000e+02,  2.50985694e+00, -6.29648626e-01, ...,
         0.00000000e+00,  0.00000000e+00, -1.54935241e-01],
       ...,
       [ 6.99980000e+02,  3.10122466e+00,  2.00371534e-01, ...,
         0.00000000e+00,  0.00000000e+00, -1.64021969e-01],
       [ 6.99990000e+02,  3.10198212e+00,  1.95461094e-01, ...,
         0.00000000e+00,  0.00000000e+00, -1.67606190e-01],
       [ 7.00000000e+02,  3.10281539e+00,  1.90550655e-01, ...,
         0.00000000e+00,  0.00000000e+00, -1.71190396e-01]])

In [4]:
# Individual columns can be accessed with dictionary style access:
output["Wind1VelX"]

array([2.50940251, 2.50962973, 2.50985694, ..., 3.10122466, 3.10198212,
       3.10281539])

In [5]:
# There are additional properties for easily accessing summary statistics of the file:
output.minima

# To be implemented: dictionary access for statistics arrays, ie. output.minima["Wind1VelX"]

array([ 1.00000000e+02,  6.17585957e-01, -2.54690242e+00, -1.65664721e+00,
        1.82391261e-03,  0.00000000e+00,  4.44834137e+00, -1.56256938e+00,
       -8.82340918e+03, -1.01468232e+04, -8.82340918e+03, -1.05159502e+04,
       -1.01468232e+04, -8.48436621e+03, -1.57903793e+02, -3.84676685e+03,
        0.00000000e+00,  5.69689810e-01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  5.49044151e+01, -6.56993774e+02,
       -2.14266205e+02, -1.79472148e+04, -1.78961426e+04, -1.79563887e+04,
       -1.75554160e+04, -1.75819473e+04, -1.75288379e+04,  3.05670508e+03,
        2.62190967e+03,  2.61701318e+03,  3.48308643e+03,  2.46614087e+03,
        2.76732422e+03, -2.09508820e+02, -2.03883041e+02, -2.07282837e+02,
        4.44834137e+00,  3.43129974e+02, -2.54771786e+01, -6.84458154e+03,
        8.93623474e+02, -4.85614926e-01, -1.53558776e-01,  0.00000000e+00,
        4.72199857e-01,  3.41934532e-01,  3.66377890e-01,  5.69689810e-01,
        4.37000990e-01,  

In [6]:
output.ranges

array([6.00000000e+02, 4.96417207e+00, 5.10802603e+00, 3.34485972e+00,
       3.59996589e+02, 3.99999952e+00, 1.25877619e+00, 3.08437169e+00,
       1.88424541e+04, 1.92382588e+04, 1.88424541e+04, 1.67333062e+04,
       1.92382588e+04, 1.79545518e+04, 3.18509598e+02, 1.84513428e+02,
       0.00000000e+00, 5.80227798e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.31385044e+02, 1.30532770e+03,
       1.52264584e+03, 3.55979219e+04, 3.55442637e+04, 3.56914961e+04,
       3.52061211e+04, 3.52300703e+04, 3.52639492e+04, 2.22526426e+04,
       2.24096470e+04, 2.23622603e+04, 2.18262632e+04, 2.25654177e+04,
       2.22119512e+04, 1.89762070e+02, 1.72259762e+02, 1.82827024e+02,
       1.25877619e+00, 7.50030182e+02, 5.14648285e+01, 1.19304473e+04,
       1.37188218e+04, 4.50254027e-01, 3.10767755e-01, 0.00000000e+00,
       5.89976794e+00, 5.83892599e+00, 5.84121174e+00, 5.80227798e+00,
       5.74385953e+00, 5.74426556e+00, 3.09549594e+00, 3.08936715e+00,
      

#### Passing OpenFAST Data in Directly

In [7]:
# test_array = np.array(
#     [
#         [1, 0, 10, 1, 2],
#         [2, 0, 10, 2, 4],
#         [3, 0, 10, 3, 6],
#         [4, 0, 10, 2, 8],
#         [5, 0, 10, 1, 4],
#     ]
# )

# output = OpenFASTOutput(data, dlc="TestDLC")